// server/index.ts
// NEXG Concierge API.
//
// PostgreSQL is the only catalogue source. If it is unavailable, health and
// catalogue routes fail visibly instead of serving a stale local copy.

import 'dotenv/config';
import express from 'express';
import type { Request, Response, NextFunction } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { initDb, isDbReady, closeDb } from './db.ts';
import * as repo from './repository.ts';
import { registerAuthRoutes } from './auth/routes.ts';
import { observabilityMiddleware, registerObservabilityRoutes } from './observability.ts';
import { rateLimit, securityHeaders, clientIp, deviceId, forwardedChain, rateLimiterStats } from './security.ts';
import { logger } from './logger.ts';
import { versionInfo } from './version.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

const app = express();
const PORT = Number(process.env.PORT ?? 3001);

// Trust exactly one hop: Cloudflare, then nginx, then this process.
//
// Express needs this to read X-Forwarded-For, but trusting too much is worse than
// trusting nothing — a caller could otherwise set the header themselves and choose which
// rate-limit bucket they land in. `1` means "trust the last proxy only", which is the
// number of proxies actually in front of us.
app.set('trust proxy', 1);

// Security headers first, so they are present even on responses generated by a limiter
// rejection or a rejected body. A 429 or a 400 is still a response a browser renders.
app.use(securityHeaders(process.env.NODE_ENV === 'production'));

// Observability is mounted ahead of everything else, including the body parser and
// the CORS handler. Mounting it after `express.json()` would drop every request the
// parser rejects from the counts, and mounting it after CORS would drop every
// preflight — the two categories of traffic that are hardest to reason about from
// application logs alone.
app.use(observabilityMiddleware());

// Rate limiting after observability, so a blocked request is still counted and traced.
// Ordered the other way, an attack would be invisible in the metrics — which is precisely
// when you most want to see it.
app.use(rateLimit);

/**
 * Resolve client identity once per request and put it where every later consumer can read
 * it: `res.locals` for the observability middleware, and the request logger.
 *
 * Resolved once rather than per-consumer, because `deviceId()` hashes the user agent when
 * no header is present, and doing that three times per request would burn CPU to compute
 * the same string — and risk three consumers disagreeing about who the caller is.
 */
app.use((req: Request, res: Response, next: NextFunction) => {
  const device = deviceId(req);
  const ip = clientIp(req);

  res.locals.clientIp = ip;
  res.locals.deviceId = device.id;
  res.locals.deviceSource = device.source;
  res.locals.forwardedChain = forwardedChain(req);

  // Debug level: this is per-request, and at info it would triple the volume of a normal
  // access log. It is still one flag away when an incident needs it.
  logger.debug('request identity', {
    method: req.method,
    path: req.path,
    ip,
    deviceId: device.id,
    deviceSource: device.source,
    forwardedChain: res.locals.forwardedChain || undefined,
  });

  next();
});

app.use(express.json({ limit: '1mb' }));

// CORS. Only the methods that actually exist are advertised (defect D-08).
app.use((req: Request, res: Response, next: NextFunction) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

// -------------------------------------------------------------------- helpers

/** Clamp pagination input so arbitrary values cannot reach the database (D-09). */
function parsePaging(rawLimit: unknown, rawOffset: unknown, defaultLimit = 50, maxLimit = 200) {
  const limit = Number.parseInt(String(rawLimit ?? ''), 10);
  const offset = Number.parseInt(String(rawOffset ?? ''), 10);
  return {
    limit: Number.isFinite(limit) ? Math.min(Math.max(limit, 1), maxLimit) : defaultLimit,
    offset: Number.isFinite(offset) ? Math.max(offset, 0) : 0,
  };
}

function requireDatabase(res: Response): boolean {
  if (isDbReady()) return true;
  res.status(503).json({ error: 'Database unavailable' });
  return false;
}

function logDatabaseFailure(route: string, err: any) {
  console.error(`[NEXG] ${route} database request failed:`, err?.message ?? err);
}

// ------------------------------------------------- observability + version
// Registered after `express.json()` because /api/telemetry reads the browser's event
// batch from the request body, and before the static/404 handlers below so these
// paths are never answered by the SPA catch-all.
registerObservabilityRoutes(app);

// Identity of the running build. Flat `versionInfo()` rather than a wrapper: every
// field is already named for what it is, and a deploy check reads this instead of
// scraping a log line.
app.get('/api/version', (_req: Request, res: Response) => {
  res.json(versionInfo());
});

// --------------------------------------------------------------------- routes

// 1. Readiness — a real PostgreSQL query must succeed for this endpoint to be healthy.
app.get('/api/health', async (_req: Request, res: Response) => {
  const timestamp = new Date().toISOString();
  if (!isDbReady()) {
    return res.status(503).json({
      status: 'unavailable',
      timestamp,
      source: 'postgres',
      postgresConnected: false,
    });
  }

  try {
    const counts = await repo.getCounts();
    return res.json({
      status: 'ok',
      timestamp,
      source: 'postgres',
      postgresConnected: true,
      ...counts,
    });
  } catch (err: any) {
    logDatabaseFailure('/api/health', err);
    return res.status(503).json({
      status: 'unavailable',
      timestamp,
      source: 'postgres',
      postgresConnected: false,
    });
  }
});

// 2. Categories (21, with nested subcategories).
app.get('/api/categories', async (_req: Request, res: Response) => {
  if (!requireDatabase(res)) return;
  try {
    return res.json({ categories: await repo.listCategories() });
  } catch (err: any) {
    logDatabaseFailure('/api/categories', err);
    return res.status(503).json({ error: 'Database unavailable' });
  }
});

// 3. Merchants, paginated + filtered.
app.get('/api/merchants', async (req: Request, res: Response) => {
  const { limit, offset } = parsePaging(req.query.limit, req.query.offset);

  if (!requireDatabase(res)) return;
  try {
    const result = await repo.listMerchants({
      category: req.query.category ? String(req.query.category) : undefined,
      subcategory: req.query.subcategory ? String(req.query.subcategory) : undefined,
      area: req.query.area ? String(req.query.area) : undefined,
      search: req.query.search ? String(req.query.search) : undefined,
      sort: req.query.sort ? String(req.query.sort) : undefined,
      limit,
      offset,
    });
    return res.json({ total: result.total, offset, limit, merchants: result.merchants });
  } catch (err: any) {
    logDatabaseFailure('/api/merchants', err);
    return res.status(503).json({ error: 'Database unavailable' });
  }
});

// 4. Merchant detail (accepts id or slug).
app.get('/api/merchants/:id', async (req: Request, res: Response) => {
  const { id } = req.params;

  if (!requireDatabase(res)) return;
  try {
    const merchant = await repo.getMerchant(id);
    if (!merchant) return res.status(404).json({ error: 'Merchant not found' });
    return res.json(merchant);
  } catch (err: any) {
    logDatabaseFailure('/api/merchants/:id', err);
    return res.status(503).json({ error: 'Database unavailable' });
  }
});

// 5. Search across merchants and items.
app.get('/api/search', async (req: Request, res: Response) => {
  const q = String(req.query.q ?? '').trim();
  if (!q) return res.status(400).json({ error: 'Query parameter "q" is required' });

  const { limit } = parsePaging(req.query.limit, 0, 20, 50);

  if (!requireDatabase(res)) return;
  try {
    return res.json({ query: q, ...(await repo.search(q, limit)) });
  } catch (err: any) {
    logDatabaseFailure('/api/search', err);
    return res.status(503).json({ error: 'Database unavailable' });
  }
});

// 6. Neighbourhoods, for filter UI.
app.get('/api/areas', async (_req: Request, res: Response) => {
  if (!requireDatabase(res)) return;
  try {
    return res.json({ areas: await repo.listAreas() });
  } catch (err: any) {
    logDatabaseFailure('/api/areas', err);
    return res.status(503).json({ error: 'Database unavailable' });
  }
});

// ------------------------------------------------------------------- auth
// Mounted before the static handler below, so /api/auth/* can never be answered by
// the SPA fallback. registerAuthRoutes calls assertAuthConfigured() internally, which
// fails the BOOT when AUTH_SECRET is missing rather than failing the first login.
registerAuthRoutes(app);

// ------------------------------------------------------------ static + errors

// Serve the built SPA when it exists, so `npm run build && npm run server`
// produces a single deployable process.
const distDir = path.resolve(REPO_ROOT, 'dist');
if (fs.existsSync(distDir)) {
  app.use(express.static(distDir));
  app.get(/^(?!\/api\/).*/, (_req: Request, res: Response) => {
    res.sendFile(path.join(distDir, 'index.html'));
  });
}

app.use((_req: Request, res: Response) => {
  res.status(404).json({ error: 'Not found' });
});

app.use((err: any, _req: Request, res: Response, _next: NextFunction) => {
  console.error('[NEXG] unhandled error:', err);
  // A body the parser rejects is the caller's fault and body-parser already labels it
  // (status 400). Answering 500 would mislead the caller AND put a permanent floor
  // under the error rate /api/metrics reports, which separates 4xx from 5xx on purpose.
  // 4xx errors are only reachable now that /api/telemetry accepts POST.
  const status = Number(err?.status ?? err?.statusCode);
  if (Number.isInteger(status) && status >= 400 && status < 500) {
    // The parser's message can quote the payload; it is logged above, not echoed.
    res.status(status).json({ error: 'Bad request' });
    return;
  }
  res.status(500).json({ error: 'Internal server error' });
});

// -------------------------------------------------------------------- startup

/** Start listening. Returns the http.Server so tests can close it. */
export async function start() {
  await initDb();
  return app.listen(PORT, () => {
    const source = isDbReady() ? 'PostgreSQL' : 'PostgreSQL unavailable; database routes return 503';
    console.log(`[NEXG] API listening on http://localhost:${PORT} (source: ${source})`);
  });
}

export { app, closeDb };

// Only auto-start when executed directly, never on import (defect D-07).
const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (invokedDirectly) {
  start().catch((err) => {
    console.error('[NEXG] failed to start:', err);
    process.exit(1);
  });

  for (const signal of ['SIGINT', 'SIGTERM'] as const) {
    process.on(signal, async () => {
      console.log(`\n[NEXG] ${signal} received, shutting down`);
      await closeDb();
      process.exit(0);
    });
  }
}
